version: '3'

services:
  backend:
    container_name: api-messenger
    image: vanillafrog/api-messenger:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      MONGODB_URI: mongodb://mongo/messenger
      SPRING_DATA_MONGODB_HOST: mongo
      MAX_FILE_SIZE: "1GB"
      MAX_REQUEST_SIZE: "1GB"
      FILE-SIZE-THRESHOLD: "2MB"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo-messenger-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "messenger"
    volumes:
      - ./mongoVolume:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge